language: php

php:
  - 7.3

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate

before_install:
  - mysql -e 'CREATE DATABASE homestead;'

# The tests nedd to be re-done
#script:
#  - vendor/bin/phpunit

service:
  - mysql
